# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='game.proto',
  package='game',
  syntax='proto3',
  serialized_pb=_b('\n\ngame.proto\x12\x04game\"\"\n\x05heart\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0b\n\x03\x65xt\x18\x02 \x01(\t\"+\n\x07\x63onnect\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12\x10\n\x08\x64\x65viceId\x18\x02 \x01(\t\"\x16\n\x04\x65xit\x12\x0e\n\x06userId\x18\x01 \x01(\t\"*\n\x08joinRoom\x12\x0e\n\x06roomId\x18\x01 \x01(\t\x12\x0e\n\x06userId\x18\x02 \x01(\t\"*\n\x08\x65xitRoom\x12\x0e\n\x06roomId\x18\x01 \x01(\t\x12\x0e\n\x06userId\x18\x02 \x01(\t\"\x1d\n\x0b\x64ismissRoom\x12\x0e\n\x06roomId\x18\x01 \x01(\t\"\x17\n\x05ready\x12\x0e\n\x06roomId\x18\x01 \x01(\t\"\'\n\x04vote\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12\x0f\n\x07otherId\x18\x02 \x01(\t\"2\n\x05speak\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\r\"6\n\x05skill\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12\x0b\n\x03sid\x18\x02 \x01(\r\x12\x10\n\x08targetId\x18\x03 \x01(\tb\x06proto3')
)




_HEART = _descriptor.Descriptor(
  name='heart',
  full_name='game.heart',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='game.heart.uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ext', full_name='game.heart.ext', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=54,
)


_CONNECT = _descriptor.Descriptor(
  name='connect',
  full_name='game.connect',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='game.connect.userId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='deviceId', full_name='game.connect.deviceId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=99,
)


_EXIT = _descriptor.Descriptor(
  name='exit',
  full_name='game.exit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='game.exit.userId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=123,
)


_JOINROOM = _descriptor.Descriptor(
  name='joinRoom',
  full_name='game.joinRoom',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='roomId', full_name='game.joinRoom.roomId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='userId', full_name='game.joinRoom.userId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=167,
)


_EXITROOM = _descriptor.Descriptor(
  name='exitRoom',
  full_name='game.exitRoom',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='roomId', full_name='game.exitRoom.roomId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='userId', full_name='game.exitRoom.userId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=169,
  serialized_end=211,
)


_DISMISSROOM = _descriptor.Descriptor(
  name='dismissRoom',
  full_name='game.dismissRoom',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='roomId', full_name='game.dismissRoom.roomId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=242,
)


_READY = _descriptor.Descriptor(
  name='ready',
  full_name='game.ready',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='roomId', full_name='game.ready.roomId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=244,
  serialized_end=267,
)


_VOTE = _descriptor.Descriptor(
  name='vote',
  full_name='game.vote',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='game.vote.userId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='otherId', full_name='game.vote.otherId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=269,
  serialized_end=308,
)


_SPEAK = _descriptor.Descriptor(
  name='speak',
  full_name='game.speak',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='game.speak.userId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='msg', full_name='game.speak.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='game.speak.type', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=310,
  serialized_end=360,
)


_SKILL = _descriptor.Descriptor(
  name='skill',
  full_name='game.skill',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='game.skill.userId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sid', full_name='game.skill.sid', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='targetId', full_name='game.skill.targetId', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=362,
  serialized_end=416,
)

DESCRIPTOR.message_types_by_name['heart'] = _HEART
DESCRIPTOR.message_types_by_name['connect'] = _CONNECT
DESCRIPTOR.message_types_by_name['exit'] = _EXIT
DESCRIPTOR.message_types_by_name['joinRoom'] = _JOINROOM
DESCRIPTOR.message_types_by_name['exitRoom'] = _EXITROOM
DESCRIPTOR.message_types_by_name['dismissRoom'] = _DISMISSROOM
DESCRIPTOR.message_types_by_name['ready'] = _READY
DESCRIPTOR.message_types_by_name['vote'] = _VOTE
DESCRIPTOR.message_types_by_name['speak'] = _SPEAK
DESCRIPTOR.message_types_by_name['skill'] = _SKILL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

heart = _reflection.GeneratedProtocolMessageType('heart', (_message.Message,), dict(
  DESCRIPTOR = _HEART,
  __module__ = 'game_pb2'
  # @@protoc_insertion_point(class_scope:game.heart)
  ))
_sym_db.RegisterMessage(heart)

connect = _reflection.GeneratedProtocolMessageType('connect', (_message.Message,), dict(
  DESCRIPTOR = _CONNECT,
  __module__ = 'game_pb2'
  # @@protoc_insertion_point(class_scope:game.connect)
  ))
_sym_db.RegisterMessage(connect)

exit = _reflection.GeneratedProtocolMessageType('exit', (_message.Message,), dict(
  DESCRIPTOR = _EXIT,
  __module__ = 'game_pb2'
  # @@protoc_insertion_point(class_scope:game.exit)
  ))
_sym_db.RegisterMessage(exit)

joinRoom = _reflection.GeneratedProtocolMessageType('joinRoom', (_message.Message,), dict(
  DESCRIPTOR = _JOINROOM,
  __module__ = 'game_pb2'
  # @@protoc_insertion_point(class_scope:game.joinRoom)
  ))
_sym_db.RegisterMessage(joinRoom)

exitRoom = _reflection.GeneratedProtocolMessageType('exitRoom', (_message.Message,), dict(
  DESCRIPTOR = _EXITROOM,
  __module__ = 'game_pb2'
  # @@protoc_insertion_point(class_scope:game.exitRoom)
  ))
_sym_db.RegisterMessage(exitRoom)

dismissRoom = _reflection.GeneratedProtocolMessageType('dismissRoom', (_message.Message,), dict(
  DESCRIPTOR = _DISMISSROOM,
  __module__ = 'game_pb2'
  # @@protoc_insertion_point(class_scope:game.dismissRoom)
  ))
_sym_db.RegisterMessage(dismissRoom)

ready = _reflection.GeneratedProtocolMessageType('ready', (_message.Message,), dict(
  DESCRIPTOR = _READY,
  __module__ = 'game_pb2'
  # @@protoc_insertion_point(class_scope:game.ready)
  ))
_sym_db.RegisterMessage(ready)

vote = _reflection.GeneratedProtocolMessageType('vote', (_message.Message,), dict(
  DESCRIPTOR = _VOTE,
  __module__ = 'game_pb2'
  # @@protoc_insertion_point(class_scope:game.vote)
  ))
_sym_db.RegisterMessage(vote)

speak = _reflection.GeneratedProtocolMessageType('speak', (_message.Message,), dict(
  DESCRIPTOR = _SPEAK,
  __module__ = 'game_pb2'
  # @@protoc_insertion_point(class_scope:game.speak)
  ))
_sym_db.RegisterMessage(speak)

skill = _reflection.GeneratedProtocolMessageType('skill', (_message.Message,), dict(
  DESCRIPTOR = _SKILL,
  __module__ = 'game_pb2'
  # @@protoc_insertion_point(class_scope:game.skill)
  ))
_sym_db.RegisterMessage(skill)


# @@protoc_insertion_point(module_scope)
