<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto

namespace Game;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>game.connect_res</code>
 */
class connect_res extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     *状态 0：成功  其他：失败
     * </pre>
     *
     * <code>uint32 status = 1;</code>
     */
    private $status = 0;

    public function __construct() {
        \GPBMetadata\Game::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     *状态 0：成功  其他：失败
     * </pre>
     *
     * <code>uint32 status = 1;</code>
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * <pre>
     *状态 0：成功  其他：失败
     * </pre>
     *
     * <code>uint32 status = 1;</code>
     */
    public function setStatus($var)
    {
        GPBUtil::checkUint32($var);
        $this->status = $var;

        return $this;
    }

}

