<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto

namespace Game;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 *DEAL = 0x2005
 * </pre>
 *
 * Protobuf type <code>game.DealResponse</code>
 */
class DealResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * 第一个可以叫地主的玩家UUID
     * </pre>
     *
     * <code>string first_rob_uuid = 1;</code>
     */
    private $first_rob_uuid = '';
    /**
     * <pre>
     * 发的手牌
     * </pre>
     *
     * <code>repeated .game.Card cards_in_hand = 2;</code>
     */
    private $cards_in_hand;
    /**
     * <pre>
     * 三张底牌
     * </pre>
     *
     * <code>repeated .game.Card three_cards = 3;</code>
     */
    private $three_cards;
    /**
     * <pre>
     *玩家剩余牌数量
     * </pre>
     *
     * <code>repeated .game.PlayerInfo players = 4;</code>
     */
    private $players;

    public function __construct() {
        \GPBMetadata\Game::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * 第一个可以叫地主的玩家UUID
     * </pre>
     *
     * <code>string first_rob_uuid = 1;</code>
     */
    public function getFirstRobUuid()
    {
        return $this->first_rob_uuid;
    }

    /**
     * <pre>
     * 第一个可以叫地主的玩家UUID
     * </pre>
     *
     * <code>string first_rob_uuid = 1;</code>
     */
    public function setFirstRobUuid($var)
    {
        GPBUtil::checkString($var, True);
        $this->first_rob_uuid = $var;
    }

    /**
     * <pre>
     * 发的手牌
     * </pre>
     *
     * <code>repeated .game.Card cards_in_hand = 2;</code>
     */
    public function getCardsInHand()
    {
        return $this->cards_in_hand;
    }

    /**
     * <pre>
     * 发的手牌
     * </pre>
     *
     * <code>repeated .game.Card cards_in_hand = 2;</code>
     */
    public function setCardsInHand(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Game\Card::class);
        $this->cards_in_hand = $arr;
    }

    /**
     * <pre>
     * 三张底牌
     * </pre>
     *
     * <code>repeated .game.Card three_cards = 3;</code>
     */
    public function getThreeCards()
    {
        return $this->three_cards;
    }

    /**
     * <pre>
     * 三张底牌
     * </pre>
     *
     * <code>repeated .game.Card three_cards = 3;</code>
     */
    public function setThreeCards(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Game\Card::class);
        $this->three_cards = $arr;
    }

    /**
     * <pre>
     *玩家剩余牌数量
     * </pre>
     *
     * <code>repeated .game.PlayerInfo players = 4;</code>
     */
    public function getPlayers()
    {
        return $this->players;
    }

    /**
     * <pre>
     *玩家剩余牌数量
     * </pre>
     *
     * <code>repeated .game.PlayerInfo players = 4;</code>
     */
    public function setPlayers(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Game\PlayerInfo::class);
        $this->players = $arr;
    }

}

