<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto

namespace Game;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 *DISMISS_ROOM = 0x1006  # 解散房间
 * </pre>
 *
 * Protobuf type <code>game.DismissRoomRequest</code>
 */
class DismissRoomRequest extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Game::initOnce();
        parent::__construct();
    }

}

