<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto

namespace Game;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * 同房其他玩家信息
 * </pre>
 *
 * Protobuf type <code>game.EnterRoomResponse.Player</code>
 */
class EnterRoomResponse_Player extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * 座位号
     * </pre>
     *
     * <code>uint32 seat = 1;</code>
     */
    private $seat = 0;
    /**
     * <pre>
     * 玩家UUID
     * </pre>
     *
     * <code>string player = 2;</code>
     */
    private $player = '';
    /**
     * <pre>
     * 玩家详细信息
     * </pre>
     *
     * <code>string info = 3;</code>
     */
    private $info = '';
    /**
     * <pre>
     * 玩家状态
     * </pre>
     *
     * <code>uint32 status = 4;</code>
     */
    private $status = 0;
    /**
     * <pre>
     * 是否在线
     * </pre>
     *
     * <code>bool is_online = 5;</code>
     */
    private $is_online = false;
    /**
     * <pre>
     * 玩家累计总分
     * </pre>
     *
     * <code>uint32 total_score = 6;</code>
     */
    private $total_score = 0;

    public function __construct() {
        \GPBMetadata\Game::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * 座位号
     * </pre>
     *
     * <code>uint32 seat = 1;</code>
     */
    public function getSeat()
    {
        return $this->seat;
    }

    /**
     * <pre>
     * 座位号
     * </pre>
     *
     * <code>uint32 seat = 1;</code>
     */
    public function setSeat($var)
    {
        GPBUtil::checkUint32($var);
        $this->seat = $var;
    }

    /**
     * <pre>
     * 玩家UUID
     * </pre>
     *
     * <code>string player = 2;</code>
     */
    public function getPlayer()
    {
        return $this->player;
    }

    /**
     * <pre>
     * 玩家UUID
     * </pre>
     *
     * <code>string player = 2;</code>
     */
    public function setPlayer($var)
    {
        GPBUtil::checkString($var, True);
        $this->player = $var;
    }

    /**
     * <pre>
     * 玩家详细信息
     * </pre>
     *
     * <code>string info = 3;</code>
     */
    public function getInfo()
    {
        return $this->info;
    }

    /**
     * <pre>
     * 玩家详细信息
     * </pre>
     *
     * <code>string info = 3;</code>
     */
    public function setInfo($var)
    {
        GPBUtil::checkString($var, True);
        $this->info = $var;
    }

    /**
     * <pre>
     * 玩家状态
     * </pre>
     *
     * <code>uint32 status = 4;</code>
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * <pre>
     * 玩家状态
     * </pre>
     *
     * <code>uint32 status = 4;</code>
     */
    public function setStatus($var)
    {
        GPBUtil::checkUint32($var);
        $this->status = $var;
    }

    /**
     * <pre>
     * 是否在线
     * </pre>
     *
     * <code>bool is_online = 5;</code>
     */
    public function getIsOnline()
    {
        return $this->is_online;
    }

    /**
     * <pre>
     * 是否在线
     * </pre>
     *
     * <code>bool is_online = 5;</code>
     */
    public function setIsOnline($var)
    {
        GPBUtil::checkBool($var);
        $this->is_online = $var;
    }

    /**
     * <pre>
     * 玩家累计总分
     * </pre>
     *
     * <code>uint32 total_score = 6;</code>
     */
    public function getTotalScore()
    {
        return $this->total_score;
    }

    /**
     * <pre>
     * 玩家累计总分
     * </pre>
     *
     * <code>uint32 total_score = 6;</code>
     */
    public function setTotalScore($var)
    {
        GPBUtil::checkUint32($var);
        $this->total_score = $var;
    }

}

