<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto

namespace Game;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>game.EnterRoomResponse</code>
 */
class EnterRoomResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * 返回进入房间结果
     * </pre>
     *
     * <code>uint32 code = 1;</code>
     */
    private $code = 0;
    /**
     * <pre>
     * 6位房间号
     * </pre>
     *
     * <code>uint32 room_id = 2;</code>
     */
    private $room_id = 0;
    /**
     * <pre>
     * 房主UUID
     * </pre>
     *
     * <code>string owner = 3;</code>
     */
    private $owner = '';
    /**
     * <pre>
     * json 创建房间参数，由具体游戏各自解析字段
     * </pre>
     *
     * <code>string kwargs = 4;</code>
     */
    private $kwargs = '';
    /**
     * <code>repeated .game.EnterRoomResponse.Player player = 5;</code>
     */
    private $player;

    public function __construct() {
        \GPBMetadata\Game::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * 返回进入房间结果
     * </pre>
     *
     * <code>uint32 code = 1;</code>
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * <pre>
     * 返回进入房间结果
     * </pre>
     *
     * <code>uint32 code = 1;</code>
     */
    public function setCode($var)
    {
        GPBUtil::checkUint32($var);
        $this->code = $var;
    }

    /**
     * <pre>
     * 6位房间号
     * </pre>
     *
     * <code>uint32 room_id = 2;</code>
     */
    public function getRoomId()
    {
        return $this->room_id;
    }

    /**
     * <pre>
     * 6位房间号
     * </pre>
     *
     * <code>uint32 room_id = 2;</code>
     */
    public function setRoomId($var)
    {
        GPBUtil::checkUint32($var);
        $this->room_id = $var;
    }

    /**
     * <pre>
     * 房主UUID
     * </pre>
     *
     * <code>string owner = 3;</code>
     */
    public function getOwner()
    {
        return $this->owner;
    }

    /**
     * <pre>
     * 房主UUID
     * </pre>
     *
     * <code>string owner = 3;</code>
     */
    public function setOwner($var)
    {
        GPBUtil::checkString($var, True);
        $this->owner = $var;
    }

    /**
     * <pre>
     * json 创建房间参数，由具体游戏各自解析字段
     * </pre>
     *
     * <code>string kwargs = 4;</code>
     */
    public function getKwargs()
    {
        return $this->kwargs;
    }

    /**
     * <pre>
     * json 创建房间参数，由具体游戏各自解析字段
     * </pre>
     *
     * <code>string kwargs = 4;</code>
     */
    public function setKwargs($var)
    {
        GPBUtil::checkString($var, True);
        $this->kwargs = $var;
    }

    /**
     * <code>repeated .game.EnterRoomResponse.Player player = 5;</code>
     */
    public function getPlayer()
    {
        return $this->player;
    }

    /**
     * <code>repeated .game.EnterRoomResponse.Player player = 5;</code>
     */
    public function setPlayer(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Game\EnterRoomResponse_Player::class);
        $this->player = $arr;
    }

}

