<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto

namespace Game;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Enter_Room_Other = 0x1015 # 其他玩家进入房间
 * </pre>
 *
 * Protobuf type <code>game.EnterRoomOtherResponse</code>
 */
class EnterRoomOtherResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * 返回进入房间结果
     * </pre>
     *
     * <code>uint32 code = 1;</code>
     */
    private $code = 0;
    /**
     * <pre>
     * 玩家UUID
     * </pre>
     *
     * <code>string player = 2;</code>
     */
    private $player = '';
    /**
     * <pre>
     * 座位号
     * </pre>
     *
     * <code>uint32 seat = 3;</code>
     */
    private $seat = 0;
    /**
     * <pre>
     * 玩家详细信息
     * </pre>
     *
     * <code>string info = 4;</code>
     */
    private $info = '';

    public function __construct() {
        \GPBMetadata\Game::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * 返回进入房间结果
     * </pre>
     *
     * <code>uint32 code = 1;</code>
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * <pre>
     * 返回进入房间结果
     * </pre>
     *
     * <code>uint32 code = 1;</code>
     */
    public function setCode($var)
    {
        GPBUtil::checkUint32($var);
        $this->code = $var;
    }

    /**
     * <pre>
     * 玩家UUID
     * </pre>
     *
     * <code>string player = 2;</code>
     */
    public function getPlayer()
    {
        return $this->player;
    }

    /**
     * <pre>
     * 玩家UUID
     * </pre>
     *
     * <code>string player = 2;</code>
     */
    public function setPlayer($var)
    {
        GPBUtil::checkString($var, True);
        $this->player = $var;
    }

    /**
     * <pre>
     * 座位号
     * </pre>
     *
     * <code>uint32 seat = 3;</code>
     */
    public function getSeat()
    {
        return $this->seat;
    }

    /**
     * <pre>
     * 座位号
     * </pre>
     *
     * <code>uint32 seat = 3;</code>
     */
    public function setSeat($var)
    {
        GPBUtil::checkUint32($var);
        $this->seat = $var;
    }

    /**
     * <pre>
     * 玩家详细信息
     * </pre>
     *
     * <code>string info = 4;</code>
     */
    public function getInfo()
    {
        return $this->info;
    }

    /**
     * <pre>
     * 玩家详细信息
     * </pre>
     *
     * <code>string info = 4;</code>
     */
    public function setInfo($var)
    {
        GPBUtil::checkString($var, True);
        $this->info = $var;
    }

}

