<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto

namespace Game;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>game.ExitRoomWebResponse</code>
 */
class ExitRoomWebResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * 返回退出房间结果
     * </pre>
     *
     * <code>uint32 code = 1;</code>
     */
    private $code = 0;
    /**
     * <pre>
     * 6位房间号
     * </pre>
     *
     * <code>uint32 room_id = 2;</code>
     */
    private $room_id = 0;
    /**
     * <pre>
     * 玩家UUID
     * </pre>
     *
     * <code>string player = 3;</code>
     */
    private $player = '';
    /**
     * <code>uint32 game_type = 4;</code>
     */
    private $game_type = 0;
    /**
     * <code>uint32 app_id = 5;</code>
     */
    private $app_id = 0;

    public function __construct() {
        \GPBMetadata\Game::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * 返回退出房间结果
     * </pre>
     *
     * <code>uint32 code = 1;</code>
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * <pre>
     * 返回退出房间结果
     * </pre>
     *
     * <code>uint32 code = 1;</code>
     */
    public function setCode($var)
    {
        GPBUtil::checkUint32($var);
        $this->code = $var;
    }

    /**
     * <pre>
     * 6位房间号
     * </pre>
     *
     * <code>uint32 room_id = 2;</code>
     */
    public function getRoomId()
    {
        return $this->room_id;
    }

    /**
     * <pre>
     * 6位房间号
     * </pre>
     *
     * <code>uint32 room_id = 2;</code>
     */
    public function setRoomId($var)
    {
        GPBUtil::checkUint32($var);
        $this->room_id = $var;
    }

    /**
     * <pre>
     * 玩家UUID
     * </pre>
     *
     * <code>string player = 3;</code>
     */
    public function getPlayer()
    {
        return $this->player;
    }

    /**
     * <pre>
     * 玩家UUID
     * </pre>
     *
     * <code>string player = 3;</code>
     */
    public function setPlayer($var)
    {
        GPBUtil::checkString($var, True);
        $this->player = $var;
    }

    /**
     * <code>uint32 game_type = 4;</code>
     */
    public function getGameType()
    {
        return $this->game_type;
    }

    /**
     * <code>uint32 game_type = 4;</code>
     */
    public function setGameType($var)
    {
        GPBUtil::checkUint32($var);
        $this->game_type = $var;
    }

    /**
     * <code>uint32 app_id = 5;</code>
     */
    public function getAppId()
    {
        return $this->app_id;
    }

    /**
     * <code>uint32 app_id = 5;</code>
     */
    public function setAppId($var)
    {
        GPBUtil::checkUint32($var);
        $this->app_id = $var;
    }

}

