<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto

namespace Game;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>game.Give_up_Request</code>
 */
class Give_up_Request extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Game::initOnce();
        parent::__construct();
    }

}

