<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto

namespace Game;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 *心跳
 * </pre>
 *
 * Protobuf type <code>game.heart</code>
 */
class heart extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     *玩家UUID
     * </pre>
     *
     * <code>string uuid = 1;</code>
     */
    private $uuid = '';
    /**
     * <pre>
     *扩展字段
     * </pre>
     *
     * <code>string ext = 2;</code>
     */
    private $ext = '';

    public function __construct() {
        \GPBMetadata\Game::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     *玩家UUID
     * </pre>
     *
     * <code>string uuid = 1;</code>
     */
    public function getUuid()
    {
        return $this->uuid;
    }

    /**
     * <pre>
     *玩家UUID
     * </pre>
     *
     * <code>string uuid = 1;</code>
     */
    public function setUuid($var)
    {
        GPBUtil::checkString($var, True);
        $this->uuid = $var;

        return $this;
    }

    /**
     * <pre>
     *扩展字段
     * </pre>
     *
     * <code>string ext = 2;</code>
     */
    public function getExt()
    {
        return $this->ext;
    }

    /**
     * <pre>
     *扩展字段
     * </pre>
     *
     * <code>string ext = 2;</code>
     */
    public function setExt($var)
    {
        GPBUtil::checkString($var, True);
        $this->ext = $var;

        return $this;
    }

}

