<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto

namespace Game;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * 提供web查询本进程的负载
 * </pre>
 *
 * Protobuf type <code>game.LoadBalanceWebResponse</code>
 */
class LoadBalanceWebResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated .game.LoadBalanceWebResponse.Unit unit = 1;</code>
     */
    private $unit;

    public function __construct() {
        \GPBMetadata\Game::initOnce();
        parent::__construct();
    }

    /**
     * <code>repeated .game.LoadBalanceWebResponse.Unit unit = 1;</code>
     */
    public function getUnit()
    {
        return $this->unit;
    }

    /**
     * <code>repeated .game.LoadBalanceWebResponse.Unit unit = 1;</code>
     */
    public function setUnit(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Game\LoadBalanceWebResponse_Unit::class);
        $this->unit = $arr;
    }

}

