<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto

namespace Game;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>game.LoadBalanceWebResponse.Unit</code>
 */
class LoadBalanceWebResponse_Unit extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * 6位房间号
     * </pre>
     *
     * <code>uint32 room_id = 1;</code>
     */
    private $room_id = 0;
    /**
     * <pre>
     *房间状态
     * </pre>
     *
     * <code>uint32 room_status = 2;</code>
     */
    private $room_status = 0;
    /**
     * <pre>
     * 在房间的玩家UUID
     * </pre>
     *
     * <code>repeated string player = 3;</code>
     */
    private $player;
    /**
     * <code>string owner = 4;</code>
     */
    private $owner = '';
    /**
     * <code>uint32 game_type = 5;</code>
     */
    private $game_type = 0;
    /**
     * <code>uint32 app_id = 6;</code>
     */
    private $app_id = 0;
    /**
     * <code>string room_uuid = 7;</code>
     */
    private $room_uuid = '';
    /**
     * <code>uint32 st = 8;</code>
     */
    private $st = 0;

    public function __construct() {
        \GPBMetadata\Game::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * 6位房间号
     * </pre>
     *
     * <code>uint32 room_id = 1;</code>
     */
    public function getRoomId()
    {
        return $this->room_id;
    }

    /**
     * <pre>
     * 6位房间号
     * </pre>
     *
     * <code>uint32 room_id = 1;</code>
     */
    public function setRoomId($var)
    {
        GPBUtil::checkUint32($var);
        $this->room_id = $var;
    }

    /**
     * <pre>
     *房间状态
     * </pre>
     *
     * <code>uint32 room_status = 2;</code>
     */
    public function getRoomStatus()
    {
        return $this->room_status;
    }

    /**
     * <pre>
     *房间状态
     * </pre>
     *
     * <code>uint32 room_status = 2;</code>
     */
    public function setRoomStatus($var)
    {
        GPBUtil::checkUint32($var);
        $this->room_status = $var;
    }

    /**
     * <pre>
     * 在房间的玩家UUID
     * </pre>
     *
     * <code>repeated string player = 3;</code>
     */
    public function getPlayer()
    {
        return $this->player;
    }

    /**
     * <pre>
     * 在房间的玩家UUID
     * </pre>
     *
     * <code>repeated string player = 3;</code>
     */
    public function setPlayer(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->player = $arr;
    }

    /**
     * <code>string owner = 4;</code>
     */
    public function getOwner()
    {
        return $this->owner;
    }

    /**
     * <code>string owner = 4;</code>
     */
    public function setOwner($var)
    {
        GPBUtil::checkString($var, True);
        $this->owner = $var;
    }

    /**
     * <code>uint32 game_type = 5;</code>
     */
    public function getGameType()
    {
        return $this->game_type;
    }

    /**
     * <code>uint32 game_type = 5;</code>
     */
    public function setGameType($var)
    {
        GPBUtil::checkUint32($var);
        $this->game_type = $var;
    }

    /**
     * <code>uint32 app_id = 6;</code>
     */
    public function getAppId()
    {
        return $this->app_id;
    }

    /**
     * <code>uint32 app_id = 6;</code>
     */
    public function setAppId($var)
    {
        GPBUtil::checkUint32($var);
        $this->app_id = $var;
    }

    /**
     * <code>string room_uuid = 7;</code>
     */
    public function getRoomUuid()
    {
        return $this->room_uuid;
    }

    /**
     * <code>string room_uuid = 7;</code>
     */
    public function setRoomUuid($var)
    {
        GPBUtil::checkString($var, True);
        $this->room_uuid = $var;
    }

    /**
     * <code>uint32 st = 8;</code>
     */
    public function getSt()
    {
        return $this->st;
    }

    /**
     * <code>uint32 st = 8;</code>
     */
    public function setSt($var)
    {
        GPBUtil::checkUint32($var);
        $this->st = $var;
    }

}

