<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto

namespace Game;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * ONLINE_STATUS = 0x1016  玩家上线离线广播
 * </pre>
 *
 * Protobuf type <code>game.OnlineStatusResponse</code>
 */
class OnlineStatusResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * 玩家UUID
     * </pre>
     *
     * <code>string player = 1;</code>
     */
    private $player = '';
    /**
     * <pre>
     * 0 离线 1 上线
     * </pre>
     *
     * <code>bool status = 2;</code>
     */
    private $status = false;

    public function __construct() {
        \GPBMetadata\Game::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * 玩家UUID
     * </pre>
     *
     * <code>string player = 1;</code>
     */
    public function getPlayer()
    {
        return $this->player;
    }

    /**
     * <pre>
     * 玩家UUID
     * </pre>
     *
     * <code>string player = 1;</code>
     */
    public function setPlayer($var)
    {
        GPBUtil::checkString($var, True);
        $this->player = $var;
    }

    /**
     * <pre>
     * 0 离线 1 上线
     * </pre>
     *
     * <code>bool status = 2;</code>
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * <pre>
     * 0 离线 1 上线
     * </pre>
     *
     * <code>bool status = 2;</code>
     */
    public function setStatus($var)
    {
        GPBUtil::checkBool($var);
        $this->status = $var;
    }

}

