<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto

namespace Game;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>game.OpposeAResponse</code>
 */
class OpposeAResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     *反A成功的玩家
     * </pre>
     *
     * <code>string player = 1;</code>
     */
    private $player = '';
    /**
     * <pre>
     *反A成功的牌
     * </pre>
     *
     * <code>repeated .game.Card cards = 2;</code>
     */
    private $cards;
    /**
     * <pre>
     *房间状态
     * </pre>
     *
     * <code>uint32 status = 3;</code>
     */
    private $status = 0;

    public function __construct() {
        \GPBMetadata\Game::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     *反A成功的玩家
     * </pre>
     *
     * <code>string player = 1;</code>
     */
    public function getPlayer()
    {
        return $this->player;
    }

    /**
     * <pre>
     *反A成功的玩家
     * </pre>
     *
     * <code>string player = 1;</code>
     */
    public function setPlayer($var)
    {
        GPBUtil::checkString($var, True);
        $this->player = $var;
    }

    /**
     * <pre>
     *反A成功的牌
     * </pre>
     *
     * <code>repeated .game.Card cards = 2;</code>
     */
    public function getCards()
    {
        return $this->cards;
    }

    /**
     * <pre>
     *反A成功的牌
     * </pre>
     *
     * <code>repeated .game.Card cards = 2;</code>
     */
    public function setCards(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Game\Card::class);
        $this->cards = $arr;
    }

    /**
     * <pre>
     *房间状态
     * </pre>
     *
     * <code>uint32 status = 3;</code>
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * <pre>
     *房间状态
     * </pre>
     *
     * <code>uint32 status = 3;</code>
     */
    public function setStatus($var)
    {
        GPBUtil::checkUint32($var);
        $this->status = $var;
    }

}

