<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto

namespace Game;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>game.OpposeARequest</code>
 */
class OpposeARequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     *反A的牌
     * </pre>
     *
     * <code>repeated .game.Card cards = 1;</code>
     */
    private $cards;

    public function __construct() {
        \GPBMetadata\Game::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     *反A的牌
     * </pre>
     *
     * <code>repeated .game.Card cards = 1;</code>
     */
    public function getCards()
    {
        return $this->cards;
    }

    /**
     * <pre>
     *反A的牌
     * </pre>
     *
     * <code>repeated .game.Card cards = 1;</code>
     */
    public function setCards(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Game\Card::class);
        $this->cards = $arr;
    }

}

