<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto

namespace Game;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * 玩家投票广播
 * </pre>
 *
 * Protobuf type <code>game.PlayerVoteResponse</code>
 */
class PlayerVoteResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>bool flag = 1;</code>
     */
    private $flag = false;
    /**
     * <code>string player = 2;</code>
     */
    private $player = '';

    public function __construct() {
        \GPBMetadata\Game::initOnce();
        parent::__construct();
    }

    /**
     * <code>bool flag = 1;</code>
     */
    public function getFlag()
    {
        return $this->flag;
    }

    /**
     * <code>bool flag = 1;</code>
     */
    public function setFlag($var)
    {
        GPBUtil::checkBool($var);
        $this->flag = $var;
    }

    /**
     * <code>string player = 2;</code>
     */
    public function getPlayer()
    {
        return $this->player;
    }

    /**
     * <code>string player = 2;</code>
     */
    public function setPlayer($var)
    {
        GPBUtil::checkString($var, True);
        $this->player = $var;
    }

}

