<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto

namespace Game;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>game.PlayerInfo</code>
 */
class PlayerInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     *玩家UUID
     * </pre>
     *
     * <code>string uuid = 1;</code>
     */
    private $uuid = '';
    /**
     * <pre>
     *玩家当前剩余牌的数量
     * </pre>
     *
     * <code>uint32 num = 2;</code>
     */
    private $num = 0;

    public function __construct() {
        \GPBMetadata\Game::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     *玩家UUID
     * </pre>
     *
     * <code>string uuid = 1;</code>
     */
    public function getUuid()
    {
        return $this->uuid;
    }

    /**
     * <pre>
     *玩家UUID
     * </pre>
     *
     * <code>string uuid = 1;</code>
     */
    public function setUuid($var)
    {
        GPBUtil::checkString($var, True);
        $this->uuid = $var;
    }

    /**
     * <pre>
     *玩家当前剩余牌的数量
     * </pre>
     *
     * <code>uint32 num = 2;</code>
     */
    public function getNum()
    {
        return $this->num;
    }

    /**
     * <pre>
     *玩家当前剩余牌的数量
     * </pre>
     *
     * <code>uint32 num = 2;</code>
     */
    public function setNum($var)
    {
        GPBUtil::checkUint32($var);
        $this->num = $var;
    }

}

