<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto

namespace Game;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * 同房其他玩家信息
 * </pre>
 *
 * Protobuf type <code>game.ReconnectResponse.Player</code>
 */
class ReconnectResponse_Player extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * 座位号
     * </pre>
     *
     * <code>int32 seat = 1;</code>
     */
    private $seat = 0;
    /**
     * <pre>
     * 玩家UUID
     * </pre>
     *
     * <code>string player = 2;</code>
     */
    private $player = '';
    /**
     * <pre>
     * 玩家详细信息
     * </pre>
     *
     * <code>string info = 3;</code>
     */
    private $info = '';
    /**
     * <pre>
     * 玩家状态（0,noready,1,ready,2,playing,3,结算）
     * </pre>
     *
     * <code>uint32 status = 4;</code>
     */
    private $status = 0;
    /**
     * <pre>
     * 是否在线
     * </pre>
     *
     * <code>uint32 is_online = 5;</code>
     */
    private $is_online = 0;
    /**
     * <pre>
     * 玩家累计总分
     * </pre>
     *
     * <code>int32 total_score = 6;</code>
     */
    private $total_score = 0;
    /**
     * <pre>
     * 玩家本局抢地主的决定
     * </pre>
     *
     * <code>int32 rob_flag = 7;</code>
     */
    private $rob_flag = 0;
    /**
     * <pre>
     * 玩家本局抢地主的分数
     * </pre>
     *
     * <code>int32 rob_score = 8;</code>
     */
    private $rob_score = 0;
    /**
     * <pre>
     * 玩家本局分数
     * </pre>
     *
     * <code>int32 score = 9;</code>
     */
    private $score = 0;
    /**
     * <pre>
     * 玩家本局炸弹次数
     * </pre>
     *
     * <code>int32 boom_cnt = 10;</code>
     */
    private $boom_cnt = 0;
    /**
     * <pre>
     * 手牌
     * </pre>
     *
     * <code>repeated .game.Card cards_in_hand = 11;</code>
     */
    private $cards_in_hand;
    /**
     * <pre>
     * 打出去的牌
     * </pre>
     *
     * <code>repeated .game.Card cards_discard = 12;</code>
     */
    private $cards_discard;

    public function __construct() {
        \GPBMetadata\Game::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * 座位号
     * </pre>
     *
     * <code>int32 seat = 1;</code>
     */
    public function getSeat()
    {
        return $this->seat;
    }

    /**
     * <pre>
     * 座位号
     * </pre>
     *
     * <code>int32 seat = 1;</code>
     */
    public function setSeat($var)
    {
        GPBUtil::checkInt32($var);
        $this->seat = $var;
    }

    /**
     * <pre>
     * 玩家UUID
     * </pre>
     *
     * <code>string player = 2;</code>
     */
    public function getPlayer()
    {
        return $this->player;
    }

    /**
     * <pre>
     * 玩家UUID
     * </pre>
     *
     * <code>string player = 2;</code>
     */
    public function setPlayer($var)
    {
        GPBUtil::checkString($var, True);
        $this->player = $var;
    }

    /**
     * <pre>
     * 玩家详细信息
     * </pre>
     *
     * <code>string info = 3;</code>
     */
    public function getInfo()
    {
        return $this->info;
    }

    /**
     * <pre>
     * 玩家详细信息
     * </pre>
     *
     * <code>string info = 3;</code>
     */
    public function setInfo($var)
    {
        GPBUtil::checkString($var, True);
        $this->info = $var;
    }

    /**
     * <pre>
     * 玩家状态（0,noready,1,ready,2,playing,3,结算）
     * </pre>
     *
     * <code>uint32 status = 4;</code>
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * <pre>
     * 玩家状态（0,noready,1,ready,2,playing,3,结算）
     * </pre>
     *
     * <code>uint32 status = 4;</code>
     */
    public function setStatus($var)
    {
        GPBUtil::checkUint32($var);
        $this->status = $var;
    }

    /**
     * <pre>
     * 是否在线
     * </pre>
     *
     * <code>uint32 is_online = 5;</code>
     */
    public function getIsOnline()
    {
        return $this->is_online;
    }

    /**
     * <pre>
     * 是否在线
     * </pre>
     *
     * <code>uint32 is_online = 5;</code>
     */
    public function setIsOnline($var)
    {
        GPBUtil::checkUint32($var);
        $this->is_online = $var;
    }

    /**
     * <pre>
     * 玩家累计总分
     * </pre>
     *
     * <code>int32 total_score = 6;</code>
     */
    public function getTotalScore()
    {
        return $this->total_score;
    }

    /**
     * <pre>
     * 玩家累计总分
     * </pre>
     *
     * <code>int32 total_score = 6;</code>
     */
    public function setTotalScore($var)
    {
        GPBUtil::checkInt32($var);
        $this->total_score = $var;
    }

    /**
     * <pre>
     * 玩家本局抢地主的决定
     * </pre>
     *
     * <code>int32 rob_flag = 7;</code>
     */
    public function getRobFlag()
    {
        return $this->rob_flag;
    }

    /**
     * <pre>
     * 玩家本局抢地主的决定
     * </pre>
     *
     * <code>int32 rob_flag = 7;</code>
     */
    public function setRobFlag($var)
    {
        GPBUtil::checkInt32($var);
        $this->rob_flag = $var;
    }

    /**
     * <pre>
     * 玩家本局抢地主的分数
     * </pre>
     *
     * <code>int32 rob_score = 8;</code>
     */
    public function getRobScore()
    {
        return $this->rob_score;
    }

    /**
     * <pre>
     * 玩家本局抢地主的分数
     * </pre>
     *
     * <code>int32 rob_score = 8;</code>
     */
    public function setRobScore($var)
    {
        GPBUtil::checkInt32($var);
        $this->rob_score = $var;
    }

    /**
     * <pre>
     * 玩家本局分数
     * </pre>
     *
     * <code>int32 score = 9;</code>
     */
    public function getScore()
    {
        return $this->score;
    }

    /**
     * <pre>
     * 玩家本局分数
     * </pre>
     *
     * <code>int32 score = 9;</code>
     */
    public function setScore($var)
    {
        GPBUtil::checkInt32($var);
        $this->score = $var;
    }

    /**
     * <pre>
     * 玩家本局炸弹次数
     * </pre>
     *
     * <code>int32 boom_cnt = 10;</code>
     */
    public function getBoomCnt()
    {
        return $this->boom_cnt;
    }

    /**
     * <pre>
     * 玩家本局炸弹次数
     * </pre>
     *
     * <code>int32 boom_cnt = 10;</code>
     */
    public function setBoomCnt($var)
    {
        GPBUtil::checkInt32($var);
        $this->boom_cnt = $var;
    }

    /**
     * <pre>
     * 手牌
     * </pre>
     *
     * <code>repeated .game.Card cards_in_hand = 11;</code>
     */
    public function getCardsInHand()
    {
        return $this->cards_in_hand;
    }

    /**
     * <pre>
     * 手牌
     * </pre>
     *
     * <code>repeated .game.Card cards_in_hand = 11;</code>
     */
    public function setCardsInHand(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Game\Card::class);
        $this->cards_in_hand = $arr;
    }

    /**
     * <pre>
     * 打出去的牌
     * </pre>
     *
     * <code>repeated .game.Card cards_discard = 12;</code>
     */
    public function getCardsDiscard()
    {
        return $this->cards_discard;
    }

    /**
     * <pre>
     * 打出去的牌
     * </pre>
     *
     * <code>repeated .game.Card cards_discard = 12;</code>
     */
    public function setCardsDiscard(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Game\Card::class);
        $this->cards_discard = $arr;
    }

}

