<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto

namespace Game;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 *Rob = 0x1024  叫地主或叫分
 * </pre>
 *
 * Protobuf type <code>game.RobRequest</code>
 */
class RobRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * 叫地主，欢乐斗地主和叫地主需要，1为叫地主，2为不叫
     * </pre>
     *
     * <code>uint32 flag = 1;</code>
     */
    private $flag = 0;
    /**
     * <pre>
     * 叫分，叫分需要
     * </pre>
     *
     * <code>uint32 score = 2;</code>
     */
    private $score = 0;

    public function __construct() {
        \GPBMetadata\Game::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * 叫地主，欢乐斗地主和叫地主需要，1为叫地主，2为不叫
     * </pre>
     *
     * <code>uint32 flag = 1;</code>
     */
    public function getFlag()
    {
        return $this->flag;
    }

    /**
     * <pre>
     * 叫地主，欢乐斗地主和叫地主需要，1为叫地主，2为不叫
     * </pre>
     *
     * <code>uint32 flag = 1;</code>
     */
    public function setFlag($var)
    {
        GPBUtil::checkUint32($var);
        $this->flag = $var;
    }

    /**
     * <pre>
     * 叫分，叫分需要
     * </pre>
     *
     * <code>uint32 score = 2;</code>
     */
    public function getScore()
    {
        return $this->score;
    }

    /**
     * <pre>
     * 叫分，叫分需要
     * </pre>
     *
     * <code>uint32 score = 2;</code>
     */
    public function setScore($var)
    {
        GPBUtil::checkUint32($var);
        $this->score = $var;
    }

}

