<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto

namespace Game;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>game.SettleForRoomResponse.PlayerData</code>
 */
class SettleForRoomResponse_PlayerData extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * 玩家UUID
     * </pre>
     *
     * <code>string player = 1;</code>
     */
    private $player = '';
    /**
     * <pre>
     * 玩家座位号
     * </pre>
     *
     * <code>uint32 seat = 2;</code>
     */
    private $seat = 0;
    /**
     * <pre>
     * 玩家总分
     * </pre>
     *
     * <code>int32 total_score = 3;</code>
     */
    private $total_score = 0;
    /**
     * <pre>
     * 玩家最高分
     * </pre>
     *
     * <code>int32 top_score = 4;</code>
     */
    private $top_score = 0;
    /**
     * <pre>
     * 玩家赢牌总次数
     * </pre>
     *
     * <code>uint32 win_total_cnt = 5;</code>
     */
    private $win_total_cnt = 0;
    /**
     * <pre>
     * 是否为房主
     * </pre>
     *
     * <code>uint32 is_owner = 6;</code>
     */
    private $is_owner = 0;
    /**
     * <pre>
     * 奖励金币
     * </pre>
     *
     * <code>uint32 rewardchip = 7;</code>
     */
    private $rewardchip = 0;
    /**
     * <pre>
     * 总炸弹次数
     * </pre>
     *
     * <code>uint32 all_boom_cnt = 8;</code>
     */
    private $all_boom_cnt = 0;
    /**
     * <pre>
     * 玩家输牌总次数
     * </pre>
     *
     * <code>uint32 lose_total_cnt = 9;</code>
     */
    private $lose_total_cnt = 0;
    /**
     * <pre>
     *玩家平局总次数
     * </pre>
     *
     * <code>uint32 dogfall_total_cnt = 10;</code>
     */
    private $dogfall_total_cnt = 0;

    public function __construct() {
        \GPBMetadata\Game::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * 玩家UUID
     * </pre>
     *
     * <code>string player = 1;</code>
     */
    public function getPlayer()
    {
        return $this->player;
    }

    /**
     * <pre>
     * 玩家UUID
     * </pre>
     *
     * <code>string player = 1;</code>
     */
    public function setPlayer($var)
    {
        GPBUtil::checkString($var, True);
        $this->player = $var;
    }

    /**
     * <pre>
     * 玩家座位号
     * </pre>
     *
     * <code>uint32 seat = 2;</code>
     */
    public function getSeat()
    {
        return $this->seat;
    }

    /**
     * <pre>
     * 玩家座位号
     * </pre>
     *
     * <code>uint32 seat = 2;</code>
     */
    public function setSeat($var)
    {
        GPBUtil::checkUint32($var);
        $this->seat = $var;
    }

    /**
     * <pre>
     * 玩家总分
     * </pre>
     *
     * <code>int32 total_score = 3;</code>
     */
    public function getTotalScore()
    {
        return $this->total_score;
    }

    /**
     * <pre>
     * 玩家总分
     * </pre>
     *
     * <code>int32 total_score = 3;</code>
     */
    public function setTotalScore($var)
    {
        GPBUtil::checkInt32($var);
        $this->total_score = $var;
    }

    /**
     * <pre>
     * 玩家最高分
     * </pre>
     *
     * <code>int32 top_score = 4;</code>
     */
    public function getTopScore()
    {
        return $this->top_score;
    }

    /**
     * <pre>
     * 玩家最高分
     * </pre>
     *
     * <code>int32 top_score = 4;</code>
     */
    public function setTopScore($var)
    {
        GPBUtil::checkInt32($var);
        $this->top_score = $var;
    }

    /**
     * <pre>
     * 玩家赢牌总次数
     * </pre>
     *
     * <code>uint32 win_total_cnt = 5;</code>
     */
    public function getWinTotalCnt()
    {
        return $this->win_total_cnt;
    }

    /**
     * <pre>
     * 玩家赢牌总次数
     * </pre>
     *
     * <code>uint32 win_total_cnt = 5;</code>
     */
    public function setWinTotalCnt($var)
    {
        GPBUtil::checkUint32($var);
        $this->win_total_cnt = $var;
    }

    /**
     * <pre>
     * 是否为房主
     * </pre>
     *
     * <code>uint32 is_owner = 6;</code>
     */
    public function getIsOwner()
    {
        return $this->is_owner;
    }

    /**
     * <pre>
     * 是否为房主
     * </pre>
     *
     * <code>uint32 is_owner = 6;</code>
     */
    public function setIsOwner($var)
    {
        GPBUtil::checkUint32($var);
        $this->is_owner = $var;
    }

    /**
     * <pre>
     * 奖励金币
     * </pre>
     *
     * <code>uint32 rewardchip = 7;</code>
     */
    public function getRewardchip()
    {
        return $this->rewardchip;
    }

    /**
     * <pre>
     * 奖励金币
     * </pre>
     *
     * <code>uint32 rewardchip = 7;</code>
     */
    public function setRewardchip($var)
    {
        GPBUtil::checkUint32($var);
        $this->rewardchip = $var;
    }

    /**
     * <pre>
     * 总炸弹次数
     * </pre>
     *
     * <code>uint32 all_boom_cnt = 8;</code>
     */
    public function getAllBoomCnt()
    {
        return $this->all_boom_cnt;
    }

    /**
     * <pre>
     * 总炸弹次数
     * </pre>
     *
     * <code>uint32 all_boom_cnt = 8;</code>
     */
    public function setAllBoomCnt($var)
    {
        GPBUtil::checkUint32($var);
        $this->all_boom_cnt = $var;
    }

    /**
     * <pre>
     * 玩家输牌总次数
     * </pre>
     *
     * <code>uint32 lose_total_cnt = 9;</code>
     */
    public function getLoseTotalCnt()
    {
        return $this->lose_total_cnt;
    }

    /**
     * <pre>
     * 玩家输牌总次数
     * </pre>
     *
     * <code>uint32 lose_total_cnt = 9;</code>
     */
    public function setLoseTotalCnt($var)
    {
        GPBUtil::checkUint32($var);
        $this->lose_total_cnt = $var;
    }

    /**
     * <pre>
     *玩家平局总次数
     * </pre>
     *
     * <code>uint32 dogfall_total_cnt = 10;</code>
     */
    public function getDogfallTotalCnt()
    {
        return $this->dogfall_total_cnt;
    }

    /**
     * <pre>
     *玩家平局总次数
     * </pre>
     *
     * <code>uint32 dogfall_total_cnt = 10;</code>
     */
    public function setDogfallTotalCnt($var)
    {
        GPBUtil::checkUint32($var);
        $this->dogfall_total_cnt = $var;
    }

}

