<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto

namespace Game;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 *SETTLEMENT_FOR_ROOM = 0x2006
 * </pre>
 *
 * Protobuf type <code>game.SettleForRoomResponse</code>
 */
class SettleForRoomResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * 判断是正常完成所有局数还是解散房间 0 投票解散结算 1 正常解散
     * </pre>
     *
     * <code>uint32 flag = 1;</code>
     */
    private $flag = 0;
    /**
     * <code>repeated .game.SettleForRoomResponse.PlayerData player_data = 2;</code>
     */
    private $player_data;

    public function __construct() {
        \GPBMetadata\Game::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * 判断是正常完成所有局数还是解散房间 0 投票解散结算 1 正常解散
     * </pre>
     *
     * <code>uint32 flag = 1;</code>
     */
    public function getFlag()
    {
        return $this->flag;
    }

    /**
     * <pre>
     * 判断是正常完成所有局数还是解散房间 0 投票解散结算 1 正常解散
     * </pre>
     *
     * <code>uint32 flag = 1;</code>
     */
    public function setFlag($var)
    {
        GPBUtil::checkUint32($var);
        $this->flag = $var;
    }

    /**
     * <code>repeated .game.SettleForRoomResponse.PlayerData player_data = 2;</code>
     */
    public function getPlayerData()
    {
        return $this->player_data;
    }

    /**
     * <code>repeated .game.SettleForRoomResponse.PlayerData player_data = 2;</code>
     */
    public function setPlayerData(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Game\SettleForRoomResponse_PlayerData::class);
        $this->player_data = $arr;
    }

}

