<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto

namespace Game;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>game.ShowAResponse</code>
 */
class ShowAResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     *亮A成功的玩家
     * </pre>
     *
     * <code>string player = 1;</code>
     */
    private $player = '';
    /**
     * <pre>
     *亮的牌
     * </pre>
     *
     * <code>.game.Card card = 2;</code>
     */
    private $card = null;
    /**
     * <pre>
     *房间状态
     * </pre>
     *
     * <code>uint32 status = 3;</code>
     */
    private $status = 0;

    public function __construct() {
        \GPBMetadata\Game::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     *亮A成功的玩家
     * </pre>
     *
     * <code>string player = 1;</code>
     */
    public function getPlayer()
    {
        return $this->player;
    }

    /**
     * <pre>
     *亮A成功的玩家
     * </pre>
     *
     * <code>string player = 1;</code>
     */
    public function setPlayer($var)
    {
        GPBUtil::checkString($var, True);
        $this->player = $var;
    }

    /**
     * <pre>
     *亮的牌
     * </pre>
     *
     * <code>.game.Card card = 2;</code>
     */
    public function getCard()
    {
        return $this->card;
    }

    /**
     * <pre>
     *亮的牌
     * </pre>
     *
     * <code>.game.Card card = 2;</code>
     */
    public function setCard(&$var)
    {
        GPBUtil::checkMessage($var, \Game\Card::class);
        $this->card = $var;
    }

    /**
     * <pre>
     *房间状态
     * </pre>
     *
     * <code>uint32 status = 3;</code>
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * <pre>
     *房间状态
     * </pre>
     *
     * <code>uint32 status = 3;</code>
     */
    public function setStatus($var)
    {
        GPBUtil::checkUint32($var);
        $this->status = $var;
    }

}

