<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto

namespace Game;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>game.skill_res</code>
 */
class skill_res extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     *玩家唯一ID
     * </pre>
     *
     * <code>string userId = 1;</code>
     */
    private $userId = '';
    /**
     * <pre>
     *状态
     * </pre>
     *
     * <code>uint32 status = 2;</code>
     */
    private $status = 0;
    /**
     * <pre>
     *技能施放对象ID
     * </pre>
     *
     * <code>string targetId = 3;</code>
     */
    private $targetId = '';

    public function __construct() {
        \GPBMetadata\Game::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     *玩家唯一ID
     * </pre>
     *
     * <code>string userId = 1;</code>
     */
    public function getUserId()
    {
        return $this->userId;
    }

    /**
     * <pre>
     *玩家唯一ID
     * </pre>
     *
     * <code>string userId = 1;</code>
     */
    public function setUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->userId = $var;

        return $this;
    }

    /**
     * <pre>
     *状态
     * </pre>
     *
     * <code>uint32 status = 2;</code>
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * <pre>
     *状态
     * </pre>
     *
     * <code>uint32 status = 2;</code>
     */
    public function setStatus($var)
    {
        GPBUtil::checkUint32($var);
        $this->status = $var;

        return $this;
    }

    /**
     * <pre>
     *技能施放对象ID
     * </pre>
     *
     * <code>string targetId = 3;</code>
     */
    public function getTargetId()
    {
        return $this->targetId;
    }

    /**
     * <pre>
     *技能施放对象ID
     * </pre>
     *
     * <code>string targetId = 3;</code>
     */
    public function setTargetId($var)
    {
        GPBUtil::checkString($var, True);
        $this->targetId = $var;

        return $this;
    }

}

