<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto

namespace Game;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>game.SpeakerResponse</code>
 */
class SpeakerResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string player = 1;</code>
     */
    private $player = '';
    /**
     * <code>string content = 2;</code>
     */
    private $content = '';

    public function __construct() {
        \GPBMetadata\Game::initOnce();
        parent::__construct();
    }

    /**
     * <code>string player = 1;</code>
     */
    public function getPlayer()
    {
        return $this->player;
    }

    /**
     * <code>string player = 1;</code>
     */
    public function setPlayer($var)
    {
        GPBUtil::checkString($var, True);
        $this->player = $var;
    }

    /**
     * <code>string content = 2;</code>
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * <code>string content = 2;</code>
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->content = $var;
    }

}

