<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto

namespace Game;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * SPONSOR_VOTE = 0x1009 发起投票解散房间
 * </pre>
 *
 * Protobuf type <code>game.SponsorVoteResponse</code>
 */
class SponsorVoteResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * 6位房间号
     * </pre>
     *
     * <code>uint32 room_id = 1;</code>
     */
    private $room_id = 0;
    /**
     * <pre>
     * 发起投票玩家UUID
     * </pre>
     *
     * <code>string sponsor = 3;</code>
     */
    private $sponsor = '';
    /**
     * <pre>
     * 投票超时时间
     * </pre>
     *
     * <code>uint32 expire_seconds = 4;</code>
     */
    private $expire_seconds = 0;

    public function __construct() {
        \GPBMetadata\Game::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * 6位房间号
     * </pre>
     *
     * <code>uint32 room_id = 1;</code>
     */
    public function getRoomId()
    {
        return $this->room_id;
    }

    /**
     * <pre>
     * 6位房间号
     * </pre>
     *
     * <code>uint32 room_id = 1;</code>
     */
    public function setRoomId($var)
    {
        GPBUtil::checkUint32($var);
        $this->room_id = $var;
    }

    /**
     * <pre>
     * 发起投票玩家UUID
     * </pre>
     *
     * <code>string sponsor = 3;</code>
     */
    public function getSponsor()
    {
        return $this->sponsor;
    }

    /**
     * <pre>
     * 发起投票玩家UUID
     * </pre>
     *
     * <code>string sponsor = 3;</code>
     */
    public function setSponsor($var)
    {
        GPBUtil::checkString($var, True);
        $this->sponsor = $var;
    }

    /**
     * <pre>
     * 投票超时时间
     * </pre>
     *
     * <code>uint32 expire_seconds = 4;</code>
     */
    public function getExpireSeconds()
    {
        return $this->expire_seconds;
    }

    /**
     * <pre>
     * 投票超时时间
     * </pre>
     *
     * <code>uint32 expire_seconds = 4;</code>
     */
    public function setExpireSeconds($var)
    {
        GPBUtil::checkUint32($var);
        $this->expire_seconds = $var;
    }

}

