<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto

namespace Game;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 *开始游戏
 * </pre>
 *
 * Protobuf type <code>game.startGame</code>
 */
class startGame extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Game::initOnce();
        parent::__construct();
    }

}

