<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto

namespace Game;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 *取牌
 * </pre>
 *
 * Protobuf type <code>game.TakeCardRequest</code>
 */
class TakeCardRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated .game.Card card = 1;</code>
     */
    private $card;

    public function __construct() {
        \GPBMetadata\Game::initOnce();
        parent::__construct();
    }

    /**
     * <code>repeated .game.Card card = 1;</code>
     */
    public function getCard()
    {
        return $this->card;
    }

    /**
     * <code>repeated .game.Card card = 1;</code>
     */
    public function setCard(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Game\Card::class);
        $this->card = $arr;
    }

}

