<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto

namespace Game;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 *投票
 * </pre>
 *
 * Protobuf type <code>game.vote</code>
 */
class vote extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     *玩家唯一ID
     * </pre>
     *
     * <code>string userId = 1;</code>
     */
    private $userId = '';
    /**
     * <pre>
     *被投票的玩家唯一ID
     * </pre>
     *
     * <code>string otherId = 2;</code>
     */
    private $otherId = '';

    public function __construct() {
        \GPBMetadata\Game::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     *玩家唯一ID
     * </pre>
     *
     * <code>string userId = 1;</code>
     */
    public function getUserId()
    {
        return $this->userId;
    }

    /**
     * <pre>
     *玩家唯一ID
     * </pre>
     *
     * <code>string userId = 1;</code>
     */
    public function setUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->userId = $var;

        return $this;
    }

    /**
     * <pre>
     *被投票的玩家唯一ID
     * </pre>
     *
     * <code>string otherId = 2;</code>
     */
    public function getOtherId()
    {
        return $this->otherId;
    }

    /**
     * <pre>
     *被投票的玩家唯一ID
     * </pre>
     *
     * <code>string otherId = 2;</code>
     */
    public function setOtherId($var)
    {
        GPBUtil::checkString($var, True);
        $this->otherId = $var;

        return $this;
    }

}

